DECLARE
    v_puzzle_id NUMBER;
BEGIN
	----------------------------------------------------------
	--СПРАВОЧНИКИ
	----------------------------------------------------------
	
	
	----------------------------------------------------------
	--УРОВНИ СЛОЖНОСТИ
	----------------------------------------------------------
	INSERT INTO DIFFICULTY_LEVELS (ID, DIFFICULTY_NAME, SIZE_NUMBER) VALUES (DIFFICULTY_LEVELS_SEQ.NEXTVAL, 'Easy', 4);
    INSERT INTO DIFFICULTY_LEVELS (ID, DIFFICULTY_NAME, SIZE_NUMBER) VALUES (DIFFICULTY_LEVELS_SEQ.NEXTVAL, 'Medium', 5);
    INSERT INTO DIFFICULTY_LEVELS (ID, DIFFICULTY_NAME, SIZE_NUMBER) VALUES (DIFFICULTY_LEVELS_SEQ.NEXTVAL, 'Hard', 6);
    INSERT INTO DIFFICULTY_LEVELS (ID, DIFFICULTY_NAME, SIZE_NUMBER) VALUES (DIFFICULTY_LEVELS_SEQ.NEXTVAL, 'Expert', 7);
	
	----------------------------------------------------------
	--ИГРОВЫЕ ДЕЙСТВИЯ
	----------------------------------------------------------
    INSERT INTO GAME_ACTIONS (ID, NAME) VALUES (GAME_ACTIONS_SEQ.NEXTVAL, 'Установка небоскреба');
    INSERT INTO GAME_ACTIONS (ID, NAME) VALUES (GAME_ACTIONS_SEQ.NEXTVAL, 'Установка пометки');
    INSERT INTO GAME_ACTIONS (ID, NAME) VALUES (GAME_ACTIONS_SEQ.NEXTVAL, 'Очистка клетки');
    INSERT INTO GAME_ACTIONS (ID, NAME) VALUES (GAME_ACTIONS_SEQ.NEXTVAL, 'Отмена хода');
    INSERT INTO GAME_ACTIONS (ID, NAME) VALUES (GAME_ACTIONS_SEQ.NEXTVAL, 'Повтор хода');
    INSERT INTO GAME_ACTIONS (ID, NAME) VALUES (GAME_ACTIONS_SEQ.NEXTVAL, 'Импорт игры');
    INSERT INTO GAME_ACTIONS (ID, NAME) VALUES (GAME_ACTIONS_SEQ.NEXTVAL, 'Экспорт игры');

	----------------------------------------------------------
	--ИГРОВЫЕ СТАТУСЫ
	----------------------------------------------------------
    INSERT INTO GAME_STATUSES VALUES (GAME_STATUSES_SEQ.NEXTVAL, 'Активна');
    INSERT INTO GAME_STATUSES VALUES (GAME_STATUSES_SEQ.NEXTVAL, 'Победа');
    INSERT INTO GAME_STATUSES VALUES (GAME_STATUSES_SEQ.NEXTVAL, 'Завершена');
    INSERT INTO GAME_STATUSES VALUES (GAME_STATUSES_SEQ.NEXTVAL, 'Истекла');
    INSERT INTO GAME_STATUSES VALUES (GAME_STATUSES_SEQ.NEXTVAL, 'Импорт');
    INSERT INTO GAME_STATUSES VALUES (GAME_STATUSES_SEQ.NEXTVAL, 'Экспорт');
    
	----------------------------------------------------------
	--ПРАВИЛА ПОДСЧЁТА ОЧКОВ
	----------------------------------------------------------
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 4, 5, 5, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 4, 10, 3, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 4, 9999, 1, 'WIN_DEFAULT');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 5, 7, 6, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 5, 15, 4, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 5, 9999, 2, 'WIN_DEFAULT');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 6, 10, 8, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 6, 15, 5, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 6, 9999, 3, 'WIN_DEFAULT');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 7, 15, 10, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 7, 25, 7, 'WIN_TIER');
	
	INSERT INTO SCORING_RULES (ID, SIZE_NUMBER, MAX_MINUTES, SCORE, RULE_TYPE)
	VALUES (SCORING_RULES_SEQ.NEXTVAL, 7, 9999, 5, 'WIN_DEFAULT');
	
	
	
	
	----------------------------------------------------------
	--СОЗДАНИЕ И ЗАПОЛНЕНИЕ ПАЗЛОВ
	----------------------------------------------------------
	
	
	----------------------------------------------------------
	--ПАЗЛ 4х4 №1
	----------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY) 
    VALUES (PUZZLES_SEQ.NEXTVAL, 1, '4421312322', 0);
	
	v_puzzle_id := PUZZLES_SEQ.CURRVAL;
	
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'TOP', 1, 2);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'TOP', 2, 3);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'TOP', 3, 3);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'TOP', 4, 1);
	
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'RIGHT', 1, 1);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'RIGHT', 2, 4);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'RIGHT', 3, 2);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'RIGHT', 4, 3);
	
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'BOTTOM', 1, 3);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'BOTTOM', 2, 1);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'BOTTOM', 3, 2);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'BOTTOM', 4, 3);
	
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'LEFT', 1, 2);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'LEFT', 2, 1);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'LEFT', 3, 2);
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE) VALUES (CLUES_SEQ.NEXTVAL, v_puzzle_id, 'LEFT', 4, 2);
    
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 1, 1, 3);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 2, 1, 2);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 3, 1, 1);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 4, 1, 4);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 1, 2, 4);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 2, 2, 3);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 3, 2, 2);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 4, 2, 1);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 1, 3, 2);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 2, 3, 1);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 3, 3, 4);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 4, 3, 3);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 1, 4, 1);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 2, 4, 4);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 3, 4, 3);
    INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE) VALUES (SOLUTIONS_SEQ.NEXTVAL, v_puzzle_id, 4, 4, 2);
    
    
    ------------------------------------------------------------
	--ПАЗЛ 4х4 №2
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 1, '7934371263', 0);
    
    
    
    INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 2);
	
	
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 2);
	
	------------------------------------------------------------
	--ПАЗЛ 4х4 №3
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 1, '8471245618', 0);
	
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 2);
	
	
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 3);
	
	------------------------------------------------------------
	--ПАЗЛ 5х5 №1
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 2, '3491233241', 0);
	
	
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 5, 1);
	
	
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 4, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 5, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 5, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 5, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 5, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 5, 3);
	
	------------------------------------------------------------
	--ПАЗЛ 5х5 №2
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 2, '7523556210', 0);
	
	
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 5, 3);

	
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 3, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 5, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 5, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 5, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 5, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 5, 3);
	
	------------------------------------------------------------
	--ПАЗЛ 6х6 №1
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 3, '5125418111', 0);
	
	
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 6, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 6, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 6, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 6, 3);
	
	
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 1, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 1, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 2, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 2, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 4, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 5, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 5, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 5, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 5, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 5, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 5, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 6, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 6, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 6, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 6, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 6, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 6, 3);
	
	------------------------------------------------------------
	--ПАЗЛ 6х6 №2
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 3, '4111256172', 0);
	
	
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 6, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 5, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 6, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 6, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 5, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 6, 3);
	
	
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 1, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 2, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 4, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 4, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 5, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 5, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 5, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 5, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 5, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 5, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 6, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 6, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 6, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 6, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 6, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 6, 4);
	
	------------------------------------------------------------
	--ПАЗЛ 7х7 №1
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 4, '9102562152', 0);
	
	
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 6, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 7, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 6, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 7, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 6, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 7, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 5, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 6, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 7, 2);
	
	
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 1, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 1, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 2, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 3, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 4, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 4, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 5, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 5, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 5, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 5, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 5, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 5, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 5, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 6, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 6, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 6, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 6, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 6, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 6, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 6, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 7, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 7, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 7, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 7, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 7, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 7, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 7, 2);
	
	------------------------------------------------------------
	--ПАЗЛ 7х7 №2
	------------------------------------------------------------
	INSERT INTO PUZZLES (ID, DIFFICULTY_LEVEL_ID, SEED, IS_DAILY)
	VALUES (PUZZLES_SEQ.NEXTVAL, 4, '4781245672', 0);
	
	
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 2, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 5, 5);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 6, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'TOP', 7, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 4, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 6, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'RIGHT', 7, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 1, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 3, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 5, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 6, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'BOTTOM', 7, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 1, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 2, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 3, 1);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 4, 2);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 5, 4);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 6, 3);
	
	INSERT INTO CLUES (ID, PUZZLE_ID, SIDE, CLUE_POSITION, VALUE)
	VALUES (CLUES_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 'LEFT', 7, 4);
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 1, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 1, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 1, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 1, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 1, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 1, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 1, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 2, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 2, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 2, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 2, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 2, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 2, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 2, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 3, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 3, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 3, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 3, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 3, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 3, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 3, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 4, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 4, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 4, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 4, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 4, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 4, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 4, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 5, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 5, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 5, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 5, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 5, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 5, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 5, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 6, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 6, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 6, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 6, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 6, 7);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 6, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 6, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 1, 7, 3);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 2, 7, 5);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 3, 7, 4);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 4, 7, 6);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 5, 7, 1);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 6, 7, 2);
	
	INSERT INTO SOLUTIONS (ID, PUZZLE_ID, COORDINATE_X, COORDINATE_Y, VALUE)
	VALUES (SOLUTIONS_SEQ.NEXTVAL, PUZZLES_SEQ.CURRVAL, 7, 7, 7);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Ошибка при добавлении пазлов: ' || SQLERRM);
END;