1. Справочник уровней сложности
CREATE TABLE DIFFICULTY_LEVELS (
    ID NUMBER PRIMARY KEY,
    DIFFICULTY_NAME VARCHAR2(50) NOT NULL,
    SIZE_NUMBER NUMBER NOT NULL
);

2. Справочник действий в игре
CREATE TABLE GAME_ACTIONS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL UNIQUE
);

3. Справочник статусов игры
CREATE TABLE GAME_STATUSES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL UNIQUE
);

4. Правила начисления очков
CREATE TABLE SCORING_RULES (
    ID NUMBER PRIMARY KEY,
    SIZE_NUMBER NUMBER NOT NULL,
    MAX_MINUTES NUMBER NOT NULL,
    SCORE NUMBER NOT NULL,
    RULE_TYPE VARCHAR2(30) NOT NULL
);

5. Таблица пользователей
CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL UNIQUE,
    USERNAME VARCHAR2(30) NOT NULL,
    FIRST_GAME_DATE DATE,
    GAMES_COUNT NUMBER NOT NULL
);

6. Таблица пазлов (головоломок)
CREATE TABLE PUZZLES (
    ID NUMBER PRIMARY KEY,
    DIFFICULTY_LEVEL_ID NUMBER NOT NULL,
    SEED CHAR(10) NOT NULL,
    IS_DAILY NUMBER NOT NULL,
    CONSTRAINT FK_PUZZLE_DIFFICULTY FOREIGN KEY (DIFFICULTY_LEVEL_ID) 
        REFERENCES DIFFICULTY_LEVELS (ID)
);

7. Таблица решений для пазлов
CREATE TABLE SOLUTIONS (
    ID NUMBER PRIMARY KEY,
    PUZZLE_ID NUMBER NOT NULL,
    COORDINATE_X NUMBER NOT NULL,
    COORDINATE_Y NUMBER NOT NULL,
    VALUE NUMBER NOT NULL,
    CONSTRAINT FK_SOLUTION_PUZZLE FOREIGN KEY (PUZZLE_ID) 
        REFERENCES PUZZLES (ID)
);

8. Таблица подсказок (Clues) по краям поля
CREATE TABLE CLUES (
    ID NUMBER PRIMARY KEY,
    PUZZLE_ID NUMBER NOT NULL,
    SIDE VARCHAR2(50) NOT NULL,
    CLUE_POSITION NUMBER NOT NULL,
    VALUE NUMBER NOT NULL,
    CONSTRAINT FK_CLUES_PUZZLE FOREIGN KEY (PUZZLE_ID) 
        REFERENCES PUZZLES (ID)
);

9. Игровые сессии
CREATE TABLE GAME_SESSIONS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PUZZLE_ID NUMBER NOT NULL,
    STATUS_ID NUMBER NOT NULL,
    START_TIME DATE DEFAULT SYSDATE NOT NULL,
    END_TIME DATE,
    STEPS_COUNT NUMBER NOT NULL,
    CONSTRAINT FK_SESSION_USER FOREIGN KEY (USER_ID) 
        REFERENCES USERS (ID),
    CONSTRAINT FK_SESSION_PUZZLE FOREIGN KEY (PUZZLE_ID) 
        REFERENCES PUZZLES (ID),
    CONSTRAINT FK_SESSION_STATUS FOREIGN KEY (STATUS_ID) 
        REFERENCES GAME_STATUSES (ID)
);


10. Ходы (шаги) игры
CREATE TABLE GAME_STEPS (
    ID NUMBER PRIMARY KEY,
    STEP_NUMBER NUMBER NOT NULL,
    SESSION_ID NUMBER NOT NULL,
    ACTION_ID NUMBER NOT NULL,
    COORDINATE_X NUMBER,
    COORDINATE_Y NUMBER,
    VALUE NUMBER,
    IS_ACTUAL NUMBER,
    STEP_TIME DATE DEFAULT SYSDATE NOT NULL,
    IS_MARK NUMBER NOT NULL,
    IS_IMPORT NUMBER NOT NULL,
    CONSTRAINT FK_STEP_SESSION FOREIGN KEY (SESSION_ID) 
        REFERENCES GAME_SESSIONS (ID),
    CONSTRAINT FK_STEP_ACTION FOREIGN KEY (ACTION_ID) 
        REFERENCES GAME_ACTIONS (ID)
);

11. Логи
CREATE TABLE LOGS (
    ID NUMBER PRIMARY KEY,
    LOG_DATE DATE DEFAULT SYSDATE NOT NULL,
    SESSION_ID NUMBER,
    LOG_TYPE VARCHAR2(200) NOT NULL,
    PROCEDURE_NAME VARCHAR2(200),
    MESSAGE VARCHAR2(4000),
    CONSTRAINT FK_LOG_SESSION FOREIGN KEY (SESSION_ID) 
        REFERENCES GAME_SESSIONS (ID)
);
